[mariadb] add galera cluster support for mariadb (#348)
* (WIP) initial galera support

Signed-off-by: Gianni Carafa <gianni.carafa@srf.ch>

* (WIP) configure wsrep for galera

Signed-off-by: Gianni Carafa <gianni.carafa@srf.ch>

* (WIP) wsrep node name and address

Signed-off-by: Gianni Carafa <gianni.carafa@srf.ch>

* (WIP) wsrep node name and address

Signed-off-by: Gianni Carafa <gianni.carafa@srf.ch>

* (WIP) do not override default entrypoint script since it does a lot

Signed-off-by: Gianni Carafa <gianni.carafa@srf.ch>

* working galera cluster, but fails on cluster resize

Signed-off-by: Gianni Carafa <gianni.carafa@srf.ch>

* fix cluster resizing issue

Signed-off-by: Gianni Carafa <gianni.carafa@srf.ch>

* fix health checks

Signed-off-by: Gianni Carafa <gianni.carafa@srf.ch>

* reorganise helm chart

Signed-off-by: Gianni Carafa <gianni.carafa@srf.ch>

* add schema for galera

Signed-off-by: Gianni Carafa <gianni.carafa@srf.ch>

* update docs

Signed-off-by: Gianni Carafa <gianni.carafa@srf.ch>

* update docs

Signed-off-by: Gianni Carafa <gianni.carafa@srf.ch>

* improve mermaid graph

Signed-off-by: Gianni Carafa <gianni.carafa@srf.ch>

* chore: update CHANGELOG.md for merged changes

Signed-off-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* Bump version from 0.4.0 to 0.5.0

---------

Signed-off-by: Gianni Carafa <gianni.carafa@srf.ch>
Signed-off-by: Gianni <gianni.carafa@srf.ch>
Signed-off-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

diff --git a/charts/mariadb/templates/statefulset.yaml b/charts/mariadb/templates/statefulset.yaml
--- a/charts/mariadb/templates/statefulset.yaml
+++ b/charts/mariadb/templates/statefulset.yaml
@@ -11,7 +11,11 @@ metadata:
     {{- toYaml . | nindent 4 }}
   {{- end }}
 spec:
+  {{- if .Values.galera.enabled }}
+  replicas: {{ .Values.galera.replicaCount }}
+  {{- else }}
   replicas: 1
+  {{- end }}
   serviceName: {{ include "mariadb.fullname" . }}
   selector:
     matchLabels:
@@ -31,13 +35,42 @@ spec:
 {{- with (include "mariadb.imagePullSecrets" .) }}
 {{- . | nindent 6 }}
 {{- end }}
-      securityContext: {{ include "cloudpirates.renderPodSecurityContext" . | nindent 8 }}
+      securityContext: {{ include "common.renderPodSecurityContext" . | nindent 8 }}
+      {{- if .Values.galera.enabled }}
+      initContainers:
+        - name: galera-config-init
+          image: {{ include "mariadb.image" . }}
+          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
+          securityContext: {{ include "common.renderContainerSecurityContext" . | nindent 12 }}
+          command:
+            - /bin/bash
+            - -c
+            - |
+              REPLICA_NUM=$(echo $HOSTNAME | grep -o '[0-9]*$')
+              cp /tmp/galera-config-ro/galera.cnf /tmp/galera-config-rw/galera.cnf
+              sed -i "s/REPLICA_NUM/$REPLICA_NUM/g" /tmp/galera-config-rw/galera.cnf
+              chmod 644 /tmp/galera-config-rw/galera.cnf
+          volumeMounts:
+            - mountPath: /tmp
+              name: tmp-volume
+            - name: galera-config
+              mountPath: /tmp/galera-config-ro
+              readOnly: true
+            - name: galera-config-rw 
+              mountPath: /tmp/galera-config-rw
+      {{- end }}
       containers:
         - name: mariadb
           image: {{ include "mariadb.image" . }}
           imagePullPolicy: {{ .Values.image.imagePullPolicy }}
-          securityContext: {{ include "cloudpirates.renderContainerSecurityContext" . | nindent 12 }}
-          {{- if or .Values.auth.enabled .Values.auth.database .Values.auth.username .Values.auth.allowEmptyRootPassword .Values.env }}
+          securityContext: {{ include "common.renderContainerSecurityContext" . | nindent 12 }}
+          {{- if .Values.galera.enabled }}
+          command: 
+            - /bin/bash
+            - -c
+            - source /usr/local/bin/galera-entrypoint.sh
+          {{- end }}
+          {{- if or .Values.auth.enabled .Values.auth.database .Values.auth.username .Values.auth.allowEmptyRootPassword .Values.env .Values.galera.enabled }}
           env:
             {{- if and .Values.auth.enabled }}
             - name: MARIADB_ROOT_PASSWORD
@@ -63,6 +96,31 @@ spec:
             - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
               value: "1"
             {{- end }}
+            {{- if .Values.galera.enabled }}
+            - name: MARIADB_GALERA_CLUSTER
+              value: "true"
+            - name: MARIADB_GALERA_CLUSTER_NAME
+              value: {{ .Values.galera.name | quote }}
+            - name: MARIADB_GALERA_NODE_NAME
+              valueFrom:
+                fieldRef:
+                  fieldPath: metadata.name
+            - name: MARIADB_GALERA_NODE_ADDRESS
+              valueFrom:
+                fieldRef:
+                  fieldPath: status.podIP
+            {{- if .Values.galera.sst.password }}
+            - name: MARIADB_GALERA_SST_USER
+              value: {{ .Values.galera.sst.user | quote }}
+            - name: MARIADB_GALERA_SST_PASSWORD
+              valueFrom:
+                secretKeyRef:
+                  name: {{ include "mariadb.galeraSecretName" . }}
+                  key: {{ .Values.galera.sst.secretKeys.passwordKey }}
+            {{- end }}
+            - name: MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP
+              value: {{ .Values.galera.forceSafeToBootstrap | quote }}
+            {{- end }}
             {{- with .Values.env }}
             {{- toYaml . | nindent 12 }}
             {{- end }}
@@ -71,20 +129,43 @@ spec:
             - name: mysql
               containerPort: 3306
               protocol: TCP
+            {{- if .Values.galera.enabled }}
+            - name: galera-repl
+              containerPort: 4567
+              protocol: TCP
+            - name: galera-ist
+              containerPort: 4568
+              protocol: TCP
+            - name: galera-sst
+              containerPort: 4444
+              protocol: TCP
+            {{- end }}
           {{- if .Values.livenessProbe.enabled }}
           livenessProbe:
             exec:
               command:
                 - bash
                 - -c
+                {{- if and .Values.galera.enabled .Values.auth.enabled }}
+                - |
+                  if mariadb -uroot -p"$MARIADB_ROOT_PASSWORD" -e "SHOW STATUS LIKE 'wsrep_ready'" | grep -q ON; then
+                    exit 0
+                  else
+                    mariadb -uroot -p"$MARIADB_ROOT_PASSWORD" -e "SHOW STATUS LIKE 'wsrep_local_state_comment'"
+                    mariadb -uroot -p"$MARIADB_ROOT_PASSWORD" -e "SHOW STATUS LIKE 'wsrep_ready'"
+                    echo "healthcheck failed: Galera not alive"
+                    exit 1
+                  fi
+                {{- else }}
                 - healthcheck.sh --connect --innodb_initialized
+                {{- end }}
             initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
             periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
             timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
             successThreshold: {{ .Values.livenessProbe.successThreshold }}
             failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
           {{- end }}
-          {{- if .Values.readinessProbe.enabled }}
+          {{- if and .Values.readinessProbe.enabled (not .Values.galera.enabled)}}
           readinessProbe:
             exec:
               command:
@@ -97,7 +178,7 @@ spec:
             successThreshold: {{ .Values.readinessProbe.successThreshold }}
             failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
           {{- end }}
-          {{- if .Values.startupProbe.enabled }}
+          {{- if and .Values.startupProbe.enabled (not .Values.galera.enabled)}}
           startupProbe:
             exec:
               command:
@@ -119,9 +200,17 @@ spec:
               mountPath: /var/lib/mysql
             - mountPath: /tmp
               name: tmp-volume
-            {{- if or .Values.config.customConfiguration .Values.config.existingConfigMap }}
+            {{- if or .Values.config.customConfiguration .Values.config.existingConfigMap .Values.galera.enabled }}
             - name: config
               mountPath: /etc/mysql/conf.d
+            {{- end }}
+            {{- if .Values.galera.enabled }}
+            - name: galera-config-rw
+              mountPath: /etc/mysql/mariadb.conf.d/60-galera.cnf
+              subPath: galera.cnf
+            - name: galera-scripts
+              mountPath: /usr/local/bin/galera-entrypoint.sh
+              subPath: galera-entrypoint.sh
             {{- end }}
             {{- if .Values.initdbScriptsConfigMap }}
             - name: custom-init-scripts
@@ -142,10 +231,21 @@ spec:
         - name: run
           emptyDir: {}
         {{- end }}
-        {{- if or .Values.config.customConfiguration .Values.config.existingConfigMap }}
+        {{- if or .Values.config.customConfiguration .Values.config.existingConfigMap .Values.galera.enabled }}
         - name: config
           configMap:
             name: {{ include "mariadb.configMapName" . }}
+        {{- end }}
+        {{- if .Values.galera.enabled }}
+        - name: galera-config
+          configMap:
+            name: {{ include "mariadb.fullname" . }}-galera
+        - name: galera-config-rw
+          emptyDir: {}
+        - name: galera-scripts
+          configMap:
+            name: {{ include "mariadb.fullname" . }}-galera-scripts
+            defaultMode: 0755
         {{- end }}
         {{- if .Values.initdbScriptsConfigMap }}
         - name: custom-init-scripts
